security:
    # 1. Configuration du hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2. Fournisseur d'utilisateur
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3. Firewalls (pare-feu)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout         # route Symfony pour la déconnexion
                target: app_login        # redirection après logout (remplace par ta route si nécessaire)

    # 4. Règles d’accès selon les rôles
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/manager, roles: ROLE_MANAGER }
        - { path: ^/coach, roles: ROLE_COACH }
        - { path: ^/nutrionniste, roles: ROLE_NUTRIONNISTE }
        - { path: ^/comptable, roles: ROLE_COMPTABLE }
        - { path: ^/adherant, roles: ROLE_ADHERANT }
        

# 5. Configuration spéciale pour les tests (rapide et légère)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4           # Pour bcrypt
                time_cost: 3      # Pour argon
                memory_cost: 10   # Pour argon
